# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  host: <%= ENV.fetch("POSTGRES_DB_HOST") { "database" } %>
  database: <%= ENV.fetch("POSTGRES_DB") { "feed_the_needy_development" } %>
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>

dev:
  <<: *default
  adapter: postgresql
  host: <%= ENV.fetch("POSTGRES_DB_HOST") { "database" } %>
  database: <%= ENV.fetch("POSTGRES_DB") { "feed_the_needy_development" } %>
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>

staging:
  <<: *default
  adapter: postgresql
  host: <%= ENV.fetch("POSTGRES_DB_HOST") { "feed_the_needy_staging" } %>
  database: <%= ENV.fetch("POSTGRES_DB") { "feed_the_needy_staging" } %>
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>

production:
  <<: *default
  adapter: postgresql
  host: <%= ENV.fetch("POSTGRES_DB_HOST") { "feed_the_needy_production" } %>
  database: <%= ENV.fetch("POSTGRES_DB") { "feed_the_needy_production" } %>
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  adapter: postgresql
  host: <%= ENV.fetch("POSTGRES_DB_HOST") { "database" } %>
  database: <%= ENV.fetch("POSTGRES_DB") { "feed_the_needy_test" } %>
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
